# coding: utf-8

"""
    AVNU API

    REST API documentation for accessing liquidity on Layer 2.  AVNU is a decentralized exchange protocol enabling the fastest and the most efficient operations in DeFi for Layer 2 with better pricing, zero slippage, MEV-protection and gasless trading.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from avnu_python_client.models.order_response_dto_frequency import OrderResponseDtoFrequency
from avnu_python_client.models.pricing_strategy import PricingStrategy
from avnu_python_client.models.trade_response_dto import TradeResponseDto
from typing import Optional, Set
from typing_extensions import Self

class OrderResponseDto(BaseModel):
    """
    OrderResponseDto
    """ # noqa: E501
    id: StrictStr = Field(description="The order identifier")
    block_number: Union[StrictFloat, StrictInt] = Field(description="The block number when the order was created", alias="blockNumber")
    timestamp: datetime = Field(description="The timestamp when the order was created")
    trader_address: StrictStr = Field(description="The trader address (hex format)", alias="traderAddress")
    order_address: StrictStr = Field(description="The order address (hex format)", alias="orderAddress")
    creation_transaction_hash: StrictStr = Field(description="The transaction hash of the order creation", alias="creationTransactionHash")
    order_class_hash: StrictStr = Field(description="The order class hash", alias="orderClassHash")
    sell_token_address: StrictStr = Field(description="The sell token address (hex format)", alias="sellTokenAddress")
    sell_amount: StrictStr = Field(description="The total amount you want to invest (hex format)", alias="sellAmount")
    sell_amount_per_cycle: StrictStr = Field(description="The amount that will be sold at each iteration (hex format)", alias="sellAmountPerCycle")
    buy_token_address: StrictStr = Field(description="The buy token address (hex format)", alias="buyTokenAddress")
    start_date: datetime = Field(description="The start date of the order", alias="startDate")
    end_date: datetime = Field(description="The end date of the order", alias="endDate")
    close_date: Optional[datetime] = Field(default=None, description="The close date of the order", alias="closeDate")
    frequency: OrderResponseDtoFrequency
    iterations: StrictInt = Field(description="The number of iterations")
    status: StrictStr = Field(description="The order status")
    pricing_strategy: Optional[PricingStrategy] = Field(default=None, alias="pricingStrategy")
    amount_sold: StrictStr = Field(description="The amount already sold", alias="amountSold")
    amount_bought: StrictStr = Field(description="The amount already bought", alias="amountBought")
    average_amount_bought: StrictStr = Field(description="The average amount sold", alias="averageAmountBought")
    executed_trades_count: StrictInt = Field(description="The number of executed trades", alias="executedTradesCount")
    cancelled_trades_count: StrictInt = Field(description="The number of cancelled trades", alias="cancelledTradesCount")
    pending_trades_count: StrictInt = Field(description="The number of pending trades", alias="pendingTradesCount")
    trades: List[TradeResponseDto] = Field(description="The trades")
    __properties: ClassVar[List[str]] = ["id", "blockNumber", "timestamp", "traderAddress", "orderAddress", "creationTransactionHash", "orderClassHash", "sellTokenAddress", "sellAmount", "sellAmountPerCycle", "buyTokenAddress", "startDate", "endDate", "closeDate", "frequency", "iterations", "status", "pricingStrategy", "amountSold", "amountBought", "averageAmountBought", "executedTradesCount", "cancelledTradesCount", "pendingTradesCount", "trades"]

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['ACTIVE', 'CLOSED']):
            raise ValueError("must be one of enum values ('ACTIVE', 'CLOSED')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of OrderResponseDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of frequency
        if self.frequency:
            _dict['frequency'] = self.frequency.to_dict()
        # override the default output from pydantic by calling `to_dict()` of pricing_strategy
        if self.pricing_strategy:
            _dict['pricingStrategy'] = self.pricing_strategy.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in trades (list)
        _items = []
        if self.trades:
            for _item_trades in self.trades:
                if _item_trades:
                    _items.append(_item_trades.to_dict())
            _dict['trades'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of OrderResponseDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "blockNumber": obj.get("blockNumber"),
            "timestamp": obj.get("timestamp"),
            "traderAddress": obj.get("traderAddress"),
            "orderAddress": obj.get("orderAddress"),
            "creationTransactionHash": obj.get("creationTransactionHash"),
            "orderClassHash": obj.get("orderClassHash"),
            "sellTokenAddress": obj.get("sellTokenAddress"),
            "sellAmount": obj.get("sellAmount"),
            "sellAmountPerCycle": obj.get("sellAmountPerCycle"),
            "buyTokenAddress": obj.get("buyTokenAddress"),
            "startDate": obj.get("startDate"),
            "endDate": obj.get("endDate"),
            "closeDate": obj.get("closeDate"),
            "frequency": OrderResponseDtoFrequency.from_dict(obj["frequency"]) if obj.get("frequency") is not None else None,
            "iterations": obj.get("iterations"),
            "status": obj.get("status"),
            "pricingStrategy": PricingStrategy.from_dict(obj["pricingStrategy"]) if obj.get("pricingStrategy") is not None else None,
            "amountSold": obj.get("amountSold"),
            "amountBought": obj.get("amountBought"),
            "averageAmountBought": obj.get("averageAmountBought"),
            "executedTradesCount": obj.get("executedTradesCount"),
            "cancelledTradesCount": obj.get("cancelledTradesCount"),
            "pendingTradesCount": obj.get("pendingTradesCount"),
            "trades": [TradeResponseDto.from_dict(_item) for _item in obj["trades"]] if obj.get("trades") is not None else None
        })
        return _obj


