# coding: utf-8

"""
    AVNU API

    REST API documentation for accessing liquidity on Layer 2.  AVNU is a decentralized exchange protocol enabling the fastest and the most efficient operations in DeFi for Layer 2 with better pricing, zero slippage, MEV-protection and gasless trading.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from avnu_python_client.models.whitelisted_call import WhitelistedCall
from typing import Optional, Set
from typing_extensions import Self

class RegisterReward(BaseModel):
    """
    RegisterReward
    """ # noqa: E501
    address: StrictStr = Field(description="The user's address")
    campaign: StrictStr = Field(description="The name of the company's campaign")
    protocol: Optional[StrictStr] = Field(default=None, description="The protocol where the reward can be used")
    free_tx: StrictInt = Field(description="The number of free transaction", alias="freeTx")
    expiration_date: Optional[datetime] = Field(default=None, description="Reward's expiration date", alias="expirationDate")
    whitelisted_calls: List[WhitelistedCall] = Field(description="The list of whitelisted calls", alias="whitelistedCalls")
    __properties: ClassVar[List[str]] = ["address", "campaign", "protocol", "freeTx", "expirationDate", "whitelistedCalls"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RegisterReward from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in whitelisted_calls (list)
        _items = []
        if self.whitelisted_calls:
            for _item_whitelisted_calls in self.whitelisted_calls:
                if _item_whitelisted_calls:
                    _items.append(_item_whitelisted_calls.to_dict())
            _dict['whitelistedCalls'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RegisterReward from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "address": obj.get("address"),
            "campaign": obj.get("campaign"),
            "protocol": obj.get("protocol"),
            "freeTx": obj.get("freeTx"),
            "expirationDate": obj.get("expirationDate"),
            "whitelistedCalls": [WhitelistedCall.from_dict(_item) for _item in obj["whitelistedCalls"]] if obj.get("whitelistedCalls") is not None else None
        })
        return _obj


