# coding: utf-8

"""
    AVNU API

    REST API documentation for accessing liquidity on Layer 2.  AVNU is a decentralized exchange protocol enabling the fastest and the most efficient operations in DeFi for Layer 2 with better pricing, zero slippage, MEV-protection and gasless trading.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List
from typing import Optional, Set
from typing_extensions import Self

class SponsorActivity(BaseModel):
    """
    SponsorActivity
    """ # noqa: E501
    name: StrictStr = Field(description="The sponsor's name")
    succeeded_tx_count: StrictInt = Field(description="The number of succeeded transactions", alias="succeededTxCount")
    reverted_tx_count: StrictInt = Field(description="The number of reverted transactions", alias="revertedTxCount")
    tx_count: StrictInt = Field(description="The total number executed transactions", alias="txCount")
    succeeded_gas_fees: StrictStr = Field(description="The amount of ETH paid for succeeded transactions", alias="succeededGasFees")
    reverted_gas_fees: StrictStr = Field(description="The amount of ETH paid for reverted transactions", alias="revertedGasFees")
    gas_fees: StrictStr = Field(description="The amount of ETH paid for all transactions", alias="gasFees")
    remaining_credits: StrictStr = Field(description="The remaining credits. When zero, please contact us so you can recharge", alias="remainingCredits")
    __properties: ClassVar[List[str]] = ["name", "succeededTxCount", "revertedTxCount", "txCount", "succeededGasFees", "revertedGasFees", "gasFees", "remainingCredits"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SponsorActivity from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SponsorActivity from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "succeededTxCount": obj.get("succeededTxCount"),
            "revertedTxCount": obj.get("revertedTxCount"),
            "txCount": obj.get("txCount"),
            "succeededGasFees": obj.get("succeededGasFees"),
            "revertedGasFees": obj.get("revertedGasFees"),
            "gasFees": obj.get("gasFees"),
            "remainingCredits": obj.get("remainingCredits")
        })
        return _obj


