# coding: utf-8

"""
    AVNU API

    REST API documentation for accessing liquidity on Layer 2.  AVNU is a decentralized exchange protocol enabling the fastest and the most efficient operations in DeFi for Layer 2 with better pricing, zero slippage, MEV-protection and gasless trading.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from avnu_python_client.models.build_swap_request import BuildSwapRequest

class TestBuildSwapRequest(unittest.TestCase):
    """BuildSwapRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BuildSwapRequest:
        """Test BuildSwapRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BuildSwapRequest`
        """
        model = BuildSwapRequest()
        if include_optional:
            return BuildSwapRequest(
                quote_id = '',
                taker_address = '0x052D8E9778D026588a51595E30B0F45609B4F771EecF0E335CdeFeD1d84a9D89',
                slippage = 0.05
            )
        else:
            return BuildSwapRequest(
                quote_id = '',
                slippage = 0.05,
        )
        """

    def testBuildSwapRequest(self):
        """Test BuildSwapRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
