# coding: utf-8

"""
    AVNU API

    REST API documentation for accessing liquidity on Layer 2.  AVNU is a decentralized exchange protocol enabling the fastest and the most efficient operations in DeFi for Layer 2 with better pricing, zero slippage, MEV-protection and gasless trading.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from avnu_python_client.api.dca_api import DCAApi


class TestDCAApi(unittest.TestCase):
    """DCAApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DCAApi()

    def tearDown(self) -> None:
        pass

    def test_build_typed_data_cancel_order(self) -> None:
        """Test case for build_typed_data_cancel_order

        Retrieve typed data to cancel DCA order
        """
        pass

    def test_build_typed_data_create_order(self) -> None:
        """Test case for build_typed_data_create_order

        Retrieve typed data to create DCA order
        """
        pass

    def test_cancel_order(self) -> None:
        """Test case for cancel_order

        Retrieve calls to cancel DCA order
        """
        pass

    def test_create_order(self) -> None:
        """Test case for create_order

        Retrieve calls to create DCA order
        """
        pass

    def test_execute_cancel_order(self) -> None:
        """Test case for execute_cancel_order

        Cancel the order
        """
        pass

    def test_execute_create_order(self) -> None:
        """Test case for execute_create_order

        Execute the order creation
        """
        pass

    def test_get_orders(self) -> None:
        """Test case for get_orders

        Find DCA orders
        """
        pass


if __name__ == '__main__':
    unittest.main()
