# coding: utf-8

"""
    AVNU API

    REST API documentation for accessing liquidity on Layer 2.  AVNU is a decentralized exchange protocol enabling the fastest and the most efficient operations in DeFi for Layer 2 with better pricing, zero slippage, MEV-protection and gasless trading.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from avnu_python_client.models.create_order_request_dto import CreateOrderRequestDto

class TestCreateOrderRequestDto(unittest.TestCase):
    """CreateOrderRequestDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateOrderRequestDto:
        """Test CreateOrderRequestDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateOrderRequestDto`
        """
        model = CreateOrderRequestDto()
        if include_optional:
            return CreateOrderRequestDto(
                trader_address = '0x49d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7',
                sell_token_address = '0x49d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7',
                sell_amount = '0x0de0b6b3a7640000',
                sell_amount_per_cycle = '0x016345785d8a0000',
                buy_token_address = '0x04718f5a0fc34cc1af16a1cdee98ffb20c31f5cd61d6ab07201858f4287c938d',
                frequency = PT24H,
                start_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                pricing_strategy = avnu_python_client.models.pricing_strategy.PricingStrategy(
                    token_to_min_amount = '', 
                    token_to_max_amount = '', )
            )
        else:
            return CreateOrderRequestDto(
                trader_address = '0x49d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7',
                sell_token_address = '0x49d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7',
                sell_amount = '0x0de0b6b3a7640000',
                sell_amount_per_cycle = '0x016345785d8a0000',
                buy_token_address = '0x04718f5a0fc34cc1af16a1cdee98ffb20c31f5cd61d6ab07201858f4287c938d',
                frequency = PT24H,
                pricing_strategy = avnu_python_client.models.pricing_strategy.PricingStrategy(
                    token_to_min_amount = '', 
                    token_to_max_amount = '', ),
        )
        """

    def testCreateOrderRequestDto(self):
        """Test CreateOrderRequestDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
