# coding: utf-8

"""
    AVNU API

    REST API documentation for accessing liquidity on Layer 2.  AVNU is a decentralized exchange protocol enabling the fastest and the most efficient operations in DeFi for Layer 2 with better pricing, zero slippage, MEV-protection and gasless trading.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from avnu_python_client.models.domain import Domain

class TestDomain(unittest.TestCase):
    """Domain unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Domain:
        """Test Domain
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Domain`
        """
        model = Domain()
        if include_optional:
            return Domain(
                name = avnu_python_client.models.json_primitive.JsonPrimitive(
                    content = '', 
                    is_string = True, ),
                version = avnu_python_client.models.json_primitive.JsonPrimitive(
                    content = '', 
                    is_string = True, ),
                chain_id = avnu_python_client.models.json_primitive.JsonPrimitive(
                    content = '', 
                    is_string = True, ),
                revision = avnu_python_client.models.json_primitive.JsonPrimitive(
                    content = '', 
                    is_string = True, ),
                resolved_revision = 'V0',
                separator_namelib = ''
            )
        else:
            return Domain(
                name = avnu_python_client.models.json_primitive.JsonPrimitive(
                    content = '', 
                    is_string = True, ),
                version = avnu_python_client.models.json_primitive.JsonPrimitive(
                    content = '', 
                    is_string = True, ),
                chain_id = avnu_python_client.models.json_primitive.JsonPrimitive(
                    content = '', 
                    is_string = True, ),
                resolved_revision = 'V0',
                separator_namelib = '',
        )
        """

    def testDomain(self):
        """Test Domain"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
