# coding: utf-8

"""
    AVNU API

    REST API documentation for accessing liquidity on Layer 2.  AVNU is a decentralized exchange protocol enabling the fastest and the most efficient operations in DeFi for Layer 2 with better pricing, zero slippage, MEV-protection and gasless trading.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from avnu_python_client.api.swap_api import SwapApi


class TestSwapApi(unittest.TestCase):
    """SwapApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SwapApi()

    def tearDown(self) -> None:
        pass

    def test_build(self) -> None:
        """Test case for build

        Build swap calldata
        """
        pass

    def test_build1(self) -> None:
        """Test case for build1

        Build swap calldata
        """
        pass

    def test_build_typed_data2(self) -> None:
        """Test case for build_typed_data2

        """
        pass

    def test_execute2(self) -> None:
        """Test case for execute2

        Execute swap
        """
        pass

    def test_get_prices(self) -> None:
        """Test case for get_prices

        Find the prices of DEX applications
        """
        pass

    def test_get_prices1(self) -> None:
        """Test case for get_prices1

        Find the prices of DEX applications
        """
        pass

    def test_get_quotes(self) -> None:
        """Test case for get_quotes

        Find the best quotes
        """
        pass

    def test_get_quotes1(self) -> None:
        """Test case for get_quotes1

        Find the best quotes
        """
        pass

    def test_get_sources(self) -> None:
        """Test case for get_sources

        Fetch the list of supported sources
        """
        pass

    def test_get_sources1(self) -> None:
        """Test case for get_sources1

        Fetch the list of supported sources
        """
        pass

    def test_get_tokens1(self) -> None:
        """Test case for get_tokens1

        Fetch supported tokens
        """
        pass

    def test_get_tokens2(self) -> None:
        """Test case for get_tokens2

        Fetch supported tokens
        """
        pass


if __name__ == '__main__':
    unittest.main()
