# coding: utf-8

"""
    AVNU API

    REST API documentation for accessing liquidity on Layer 2.  AVNU is a decentralized exchange protocol enabling the fastest and the most efficient operations in DeFi for Layer 2 with better pricing, zero slippage, MEV-protection and gasless trading.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from avnu_python_client.models.page_action_dto import PageActionDto

class TestPageActionDto(unittest.TestCase):
    """PageActionDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PageActionDto:
        """Test PageActionDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PageActionDto`
        """
        model = PageActionDto()
        if include_optional:
            return PageActionDto(
                content = [
                    avnu_python_client.models.action_dto.ActionDto(
                        block_number = 56, 
                        date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        transaction_hash = '', 
                        gas_fee = avnu_python_client.models.gas_fee_info.GasFeeInfo(
                            gas_fee_amount = '', 
                            gas_fee_amount_usd = 1.337, 
                            gas_fee_token_address = '', ), 
                        type = 'Swap', 
                        metadata = avnu_python_client.models.metadata.metadata(), )
                    ],
                size = 56,
                number = 56,
                total_elements = 56,
                total_pages = 56
            )
        else:
            return PageActionDto(
                content = [
                    avnu_python_client.models.action_dto.ActionDto(
                        block_number = 56, 
                        date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        transaction_hash = '', 
                        gas_fee = avnu_python_client.models.gas_fee_info.GasFeeInfo(
                            gas_fee_amount = '', 
                            gas_fee_amount_usd = 1.337, 
                            gas_fee_token_address = '', ), 
                        type = 'Swap', 
                        metadata = avnu_python_client.models.metadata.metadata(), )
                    ],
                size = 56,
                number = 56,
                total_elements = 56,
                total_pages = 56,
        )
        """

    def testPageActionDto(self):
        """Test PageActionDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
