# coding: utf-8

"""
    AVNU API

    REST API documentation for accessing liquidity on Layer 2.  AVNU is a decentralized exchange protocol enabling the fastest and the most efficient operations in DeFi for Layer 2 with better pricing, zero slippage, MEV-protection and gasless trading.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from avnu_python_client.api.starknet_api import StarknetApi


class TestStarknetApi(unittest.TestCase):
    """StarknetApi unit test stubs"""

    def setUp(self) -> None:
        self.api = StarknetApi()

    def tearDown(self) -> None:
        pass

    def test_get_token_info(self) -> None:
        """Test case for get_token_info

        """
        pass

    def test_get_tokens(self) -> None:
        """Test case for get_tokens

        """
        pass


if __name__ == '__main__':
    unittest.main()
