# coding: utf-8

"""
    AVNU API

    REST API documentation for accessing liquidity on Layer 2.  AVNU is a decentralized exchange protocol enabling the fastest and the most efficient operations in DeFi for Layer 2 with better pricing, zero slippage, MEV-protection and gasless trading.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from avnu_python_client.models.create_order_request_dto_frequency_units_inner_duration import CreateOrderRequestDtoFrequencyUnitsInnerDuration

class TestCreateOrderRequestDtoFrequencyUnitsInnerDuration(unittest.TestCase):
    """CreateOrderRequestDtoFrequencyUnitsInnerDuration unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateOrderRequestDtoFrequencyUnitsInnerDuration:
        """Test CreateOrderRequestDtoFrequencyUnitsInnerDuration
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateOrderRequestDtoFrequencyUnitsInnerDuration`
        """
        model = CreateOrderRequestDtoFrequencyUnitsInnerDuration()
        if include_optional:
            return CreateOrderRequestDtoFrequencyUnitsInnerDuration(
                seconds = 56,
                zero = True,
                nano = 56,
                negative = True
            )
        else:
            return CreateOrderRequestDtoFrequencyUnitsInnerDuration(
        )
        """

    def testCreateOrderRequestDtoFrequencyUnitsInnerDuration(self):
        """Test CreateOrderRequestDtoFrequencyUnitsInnerDuration"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
