# coding: utf-8

"""
    AVNU API

    REST API documentation for accessing liquidity on Layer 2.  AVNU is a decentralized exchange protocol enabling the fastest and the most efficient operations in DeFi for Layer 2 with better pricing, zero slippage, MEV-protection and gasless trading.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from avnu_python_client.models.register_reward import RegisterReward

class TestRegisterReward(unittest.TestCase):
    """RegisterReward unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RegisterReward:
        """Test RegisterReward
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RegisterReward`
        """
        model = RegisterReward()
        if include_optional:
            return RegisterReward(
                address = '0x039321741034d079C573bAd24dB5F012ed9614554301a2B08bDcb34E01d9C1BF',
                campaign = 'Onboarding',
                protocol = 'AVNU',
                free_tx = 10,
                expiration_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                whitelisted_calls = [
                    avnu_python_client.models.whitelisted_call.WhitelistedCall(
                        contract_address = '*', 
                        entrypoint = 'approve', )
                    ]
            )
        else:
            return RegisterReward(
                address = '0x039321741034d079C573bAd24dB5F012ed9614554301a2B08bDcb34E01d9C1BF',
                campaign = 'Onboarding',
                free_tx = 10,
                whitelisted_calls = [
                    avnu_python_client.models.whitelisted_call.WhitelistedCall(
                        contract_address = '*', 
                        entrypoint = 'approve', )
                    ],
        )
        """

    def testRegisterReward(self):
        """Test RegisterReward"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
