# coding: utf-8

"""
    AVNU API

    REST API documentation for accessing liquidity on Layer 2.  AVNU is a decentralized exchange protocol enabling the fastest and the most efficient operations in DeFi for Layer 2 with better pricing, zero slippage, MEV-protection and gasless trading.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from avnu_python_client.models.page_token_dto import PageTokenDto

class TestPageTokenDto(unittest.TestCase):
    """PageTokenDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PageTokenDto:
        """Test PageTokenDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PageTokenDto`
        """
        model = PageTokenDto()
        if include_optional:
            return PageTokenDto(
                content = [
                    avnu_python_client.models.token_dto.TokenDto(
                        name = '', 
                        address = '', 
                        symbol = '', 
                        decimals = 56, 
                        logo_uri = '', 
                        last_daily_volume_usd = 1.337, 
                        extensions = {
                            'key' : ''
                            }, 
                        tags = [
                            'Unknown'
                            ], )
                    ],
                size = 56,
                number = 56,
                total_elements = 56,
                total_pages = 56
            )
        else:
            return PageTokenDto(
                content = [
                    avnu_python_client.models.token_dto.TokenDto(
                        name = '', 
                        address = '', 
                        symbol = '', 
                        decimals = 56, 
                        logo_uri = '', 
                        last_daily_volume_usd = 1.337, 
                        extensions = {
                            'key' : ''
                            }, 
                        tags = [
                            'Unknown'
                            ], )
                    ],
                size = 56,
                number = 56,
                total_elements = 56,
                total_pages = 56,
        )
        """

    def testPageTokenDto(self):
        """Test PageTokenDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
